server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: event-tracking-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/event_tracker}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}

logging:
  level:
    root: INFO
    com.enriqueibarraig: ${APP_LOG_LEVEL:INFO}